### ISSUE TITLE
High level interface

### ISSUE THREAD

**Issue by apuignav** [zfit/phasespace#15]
@mayou36 We discussed yesterday and I already forgot what we wanted to do. Let me write down what I remember:
  - We have a `generate` function that accepts
    + `n` as `int` or `tf.Variable`. Internally, it converts n to `tf.Variable` if it's an `int`.
    + Has a `lazy` optional parameter. 
    + Has a `chunk_size` optional parameter.
    This is the highest level function, and the one that users will usually make use of.
  - We have a `generate_tensor` (let's improve the name) that explicitly requires the `tf.Variable` and always returns a tensor. Internally, `generate` calls `generate_tensor` and does the loop. 

Is this it?

**Comment by apuignav** [comment]
@mayou36 Have you had a chance to look at this?

**Comment by mayou36** [comment]
What exactly should the chunk_size do though? return a python iterator? This also implies that it is not usable when having `lazy=False`, since the chunking would mean to just recall this parameter.

Probably leaving away the lazy and using another function (`generate_tensor` is not too bad I think) is better? Now that I think about it

**Comment by apuignav** [comment]
> This also implies that it is not usable when having lazy=False, since the chunking would mean to just recall this parameter.

I'm not sure I understand. My idea is that `chunk_size` would return an iterator, in the casy of `lazy=True` a tensor and in the case of `False` the sample itself with size `chunk_size`.

This would be a sort of "catch-all" function, and then we could have `generate_tensor` for more specialised use.

**Comment by mayou36** [comment]
Yes, but a generator does not make sense for a chuncked tensor, since it is gonna be the same tensor again. The whole method creates a tensor that, when run, evaluates (including all the randoms) newly. If we chunk without lazy, the generator has this tensor and yields each time `sess.run(tensor)`, which is clean. But a generator in lazy mode would just be `yield tensor` (the same).

So I think, for a clean API, its better to have two independent functions since they actually don't have a lot in common. One `generate` (or generate_numpy?) and another to generate the tensor. So that generate(_numpy) handles the iterator creation, the variable creation etc.

**Comment by apuignav** [comment]
OK, now that #16 is merged, we need to get to this. What are your final thoughts on it?

**Comment by mayou36** [comment]
I tend to drop the direct numpy support and have the following:
`generate` as a high level interface, that returns a tensor. Automatic caching inside (primitive) and saving n as a tf.Variable.

For the user, this is a lazy evaluated object, so phasespace.run() will do the trick. And on generator: This will then also be left to the user. But it's a simple for loop. On the other hand, if we provide a generator, a user has to write it's for loop anyway as well. Right?

On the phasespace.run: let's write in the examples always `phasespace.run` and remark that it returns a tensor actually. So who understands tensors understands what happens, everyone else will just use it as `phasespace.run(particle.generate(...))` "blindly". Or, worst case, we still put a flag there later, like `as_numpy`.

Second, having a function internal that does not cache or use tf.Variable (for the advanced usage).

I am not 100% convinced. But it seems cleaner to me than anything else. Your thoughts?

**Comment by apuignav** [comment]
I mostly agree: we should have `generate` that returns a tensor and have the `as_numpy` flag to run the `tf.Session.run` if needed. It would also convert `n` to a `tf.Variable` if it's an int. Then, maybe we could have a `create_generator` function with same arguments + some sort of chunk size? SImilarly to what we did in sampling, would that be enough?

Then, for advanced usage we either use another flag `no_autoconvert` or a special function, but it would basically be the same as before?

**Comment by mayou36** [comment]
Now I remember what we had in mind: we may have something like `phasespace.generate` (or even a different name) that generates (but no autoconversion, pure Tensor), but for the user we should create light wrapper around that low level function, something like "Decay" (yeah, different name). This has then `Decay(top, [daugthers]).generate(n_events)` (with `tf.Variable` wrapping of `n_events`, with an "as_numpy" flag etc. This also allows to cache the tensor inside.

**Comment by apuignav** [comment]
Mmm, I think I am lost. We have two things:
  - `Particle` class, which has a `generate` function.
  - `phasespace.generate`, which essentially builds a `Particle` but with a simpler interface, as it simply gets the masses of the childen particle. Following what you proposed, it is `phasespace.generate(top_mass, [children_masses])`, but the class makes sense as it allows you to cache.

However, the interfaces of these two ways of using phasespace should basically be the same thing. That is:
  - Return a tensor by default. Use the `as_numpy` flag to do the `tf.Session.run`. The tensor is cached inside.
  - `n_events` can be `int` or `tf.Variable`. if it's `int`, it gets automatically wrapped.
  - Support for `chunk_size` to return an iterator, similar to the `pandas` interface. This iterator controls the `tf.Variable` (I would say internally).

Does this cover all the cases?

**Comment by apuignav** [comment]
Closed by #18.
