### ISSUE TITLE
Stricter user-facing interface

### ISSUE THREAD

**Issue by apuignav** [zfit/phasespace#16]
Right now, user can provide a tensor of input momenta to `generate`. This is then used to calculate the number of events (if `n_events` is not given) and events are generated according to these momenta.

The proposal is to remove the `momentum` argument and simply use the mass of the top `Particle`, and add an additional `boost` argument to the user-facing functions such that the generated events are boosted afterwards. This would be needed in all methods discussed in #15.

This makes generation much simpler (everything is built from particle at rest, so accept-reject procedures can simply throw events away and generate again) while at the same time providing the possibility to generate physics-like distributions.

**Comment by apuignav** [comment]
Ping @mayou36

**Comment by mayou36** [comment]
Sorry, overlooked! Yes, that sounds reasonable. It's basically replacing `momentum` with `boost` and using n events to generate actually, right? So the changes are really minimal. And it allow the same freedom to users (boost is gonna be a tensor of (optionally) n events, right?).

Only thing: do we expect the user to know the boost or add a convenience function to convert momenta and mass to boost?

**Comment by apuignav** [comment]
Good point, maybe we could do `boost_to`, and then they can just give the mother momentum. Does it make sense?

**Comment by mayou36** [comment]
yes, something like this. Probably `boost_velocity` and `boost_momentum` as arguments? (a little shorter, better, but having two ways of boosting basically)
